### ISSUE TITLE
single quote can't be escaped

### ISSUE THREAD

**Issue by newswim** [orktes/atom-react#186] opened 2016-08-04 14:36 UTC
Hello - I did a fresh install of Atom-React. This could possibly be coming from another package, but here's what I'm seeing:

![Single Quote Bug](http://s32.postimg.org/j4dq40x2t/react_atom_single_quote_bug.png)

**Comment by aihornmac** [comment] 2016-08-05 13:14
+1

**Comment by orktes** [comment] 2016-08-07 17:17
Duplicate of https://github.com/orktes/atom-react/issues/3

**Closed by orktes** 2016-08-07 17:17 UTC
