### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tokenAtBufferColumn' of undefined

### ISSUE THREAD

**Issue by mattdeboard** [orktes/atom-react#50] opened 2015-04-07 13:37 UTC
**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [react](https://github.com/orktes/atom-react) package, v0.11.1

### Stack Trace

Uncaught TypeError: Cannot read property 'tokenAtBufferColumn' of undefined

```
At /Users/mdeboard/Downloads/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:565

TypeError: Cannot read property 'tokenAtBufferColumn' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenForPosition (/Users/mdeboard/Downloads/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:565:38)
  at DisplayBuffer.module.exports.DisplayBuffer.tokenForBufferPosition (/Users/mdeboard/Downloads/Atom.app/Contents/Resources/app/src/display-buffer.js:1061:35)
  at TextEditor.module.exports.TextEditor.tokenForBufferPosition (/Users/mdeboard/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:2464:33)
  at AtomReact.autoCloseTag (/Users/mdeboard/.atom/packages/react/lib/atom-react.coffee:212:22)
  at /Users/mdeboard/.atom/packages/react/lib/atom-react.coffee:268:26
  at Emitter.module.exports.Emitter.emit (/Users/mdeboard/Downloads/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Users/mdeboard/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:594:20)
  at BufferPatch.module.exports.BufferPatch.applyTo (/Users/mdeboard/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/buffer-patch.js:57:21)
  at Transaction.module.exports.Transaction.applyTo (/Users/mdeboard/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/transaction.js:60:29)
  at History.module.exports.History.abortTransaction (/Users/mdeboard/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:169:24)
  at History.module.exports.History.transact (/Users/mdeboard/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:126:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Users/mdeboard/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Users/mdeboard/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:1211:26)
  at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Users/mdeboard/Downloads/Atom.app/Contents/Resources/app/src/text-editor-component.js:422:35)
  at HTMLDivElement.<anonymous> (/Users/mdeboard/Downloads/Atom.app/Contents/Resources/app/src/text-editor-component.js:3:61)

```

### Commands

```
     -0:07.8 core:select-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:06.4 core:select-up (atom-text-editor.editor.is-focused.autocomplete-active)
  7x -0:06.1 core:select-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:04.4 core:select-left (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:04.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:03.2 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "atomic-emacs"
    ]
  },
  "react": {}
}
```

### Installed Packages

```coffee
# User
atom-text-transformer, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.1
autocomplete-snippets, v1.2.0
coffee-compile, v0.11.0
color-picker, v1.6.0
editorconfig, v0.3.3
highlight-line, v0.10.1
language-elixir, v0.3.4
minimap, v4.7.5
minimap-git-diff, v4.1.2
minimap-selection, v4.2.0
pretty-json, v0.3.2
react, v0.11.1
refactor, v0.4.1
seti-syntax, v0.3.3
seti-ui, v0.6.3
terminal-panel, v1.10.0

# Dev
No dev packages
```

**Comment by orktes** [comment] 2015-04-07 16:25
Could not reproduce, but added possible guards for situations that might cause it. If you are still able to reproduce please reopen the issue.

**Comment by MoOx** [comment] 2015-04-22 05:02
I was converting some jade to react and got this issue.
I am now unable to close my div (see where I add  the `<----- HERE`)

```js
import React, {Component, PropTypes} from "react"

import Navigation from "../Navigation"

export default class Header extends Component {

  static displayName = "Header"

  static contextTypes = {
    i18n: PropTypes.object,
  }

  render() {
    return (
      <div className="putainde-Header">
        <div className="r-Grid">
          <div className="r-Grid-cell r-all--3of12">
            p.putainde-Footer-text
              | #{lang.copyright.replace('{*}', new Date().getFullYear())}
          </div>
          <div className="r-Grid-cell r-all--6of12">
            if lang.footerNavigation
              ul.putainde-Footer-list
                each item in lang.footerNavigation
                  li
                    a(href="#{uri(item.url, page)}")
                      | #{item.name}
                li
                  a(href="#{lang.github}", data-cssr-tooltip="GitHub").cssr-Tooltip.cssr-Tooltip--top
                    +Icon("github")
                li
                  a(href="#{lang.twitter}", data-cssr-tooltip="Twitter").cssr-Tooltip.cssr-Tooltip--top
                    +Icon("twitter")
            </div<----- HERE
            <div className="r-Grid-cell r-all--3of12">
            p.putainde-Footer-text.putainde-Footer-text--small.putainde-Footer-text--right
              | #{lang.madeWithHeart}

          </div>
        </div>
      </div>
    )
  }
}
```

**Comment by MoOx** [comment] 2015-04-22 05:02
I had to disable this package so I can close it :)

**Comment by orktes** [comment] 2015-04-22 06:55
Hmm I copy+pasted you code but I'm unable to reproduce :( Might be something in atom-core causing this so going to figure out more guards against this.

**Comment by MoOx** [comment] 2015-04-22 07:03
Yeah I can't reproduce it myself :/

**Comment by orktes** [comment] 2015-04-22 07:25
I might be that for some reason the buffer was not fully tokenised. Added more tolerant way of getting the current token. https://github.com/orktes/atom-react/commit/1399c173bafe259e93d58feb7d37def228250b1f

**Comment by orktes** [comment] 2015-04-22 07:27
As I had no way to reproduce the issue I'll close this for now.

**Closed by orktes** 2015-04-22 07:27 UTC
