### ISSUE TITLE
Format error for comparisons: ...<...

### ISSUE THREAD

**Issue by KaiHufenbach** [orktes/atom-react#87] opened 2015-08-07 09:15 UTC
Hi, thanks for the great work!

Please have a look at that:

![image](https://cloud.githubusercontent.com/assets/959063/9132647/4eab8620-3cf5-11e5-938b-50efc4b6f4c0.png)

If you think thats all, have a look at this when trying to do another comparison in error state:

![image](https://cloud.githubusercontent.com/assets/959063/9132685/8b13175e-3cf5-11e5-9972-fd9178cac82f.png)

**Comment by orktes** [comment] 2015-08-18 06:14
Hi! Thanks for reporting! This might be dupe of https://github.com/orktes/atom-react/issues/78 so I'll close this one.

Ps. in the mean while you can use spaces to fix the issue  ìf (i < 5) {`

**Closed** 2015-08-18 06:14 UTC
