### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by fejlfri** [orktes/atom-react#28] opened 2015-01-28 14:54 UTC
Unfortunately I can't reproduce the error.

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.1
**Thrown From**: [react](https://github.com/orktes/atom-react) package, v0.9.5

### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:124

TypeError: Cannot read property 'match' of undefined
  at TextEditor.module.exports.TextEditor.isBufferRowCommented (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2427:55)
  at LanguageMode.editor.languageMode.suggestedIndentForBufferRow (/Users/daniel/.atom/packages/react/lib/atom-react.coffee:57:62)
  at LanguageMode.module.exports.LanguageMode.autoIndentBufferRow (/Applications/Atom.app/Contents/Resources/app/src/language-mode.js:374:26)
  at TextEditor._results.push._this.(anonymous function) [as autoIndentBufferRow] (/Applications/Atom.app/Contents/Resources/app/node_modules/delegato/lib/delegator.js:67:61)
  at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:478:21)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:773:31
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:812:27
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1181:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:805:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:770:21)
  at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditor.module.exports.TextEditor.insertNewline (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:789:19)
  at TextEditor.object.(anonymous function) [as insertNewline] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.editor:newline (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:590:19)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:305:34
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1181:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
  5x -6:35.1 core:backspace (atom-text-editor.editor)
     -6:19.4 core:save (atom-text-editor.editor)
     -4:50.1 core:move-left (atom-text-editor.editor)
     -4:45.7 core:copy (atom-text-editor.editor)
     -4:44.5 core:paste (atom-text-editor.editor)
     -4:44.1 core:save (atom-text-editor.editor)
  2x -1:27.6 core:copy (atom-text-editor.editor)
     -1:08.3 find-and-replace:show (atom-text-editor.editor)
     -1:07.9 core:paste (atom-text-editor.editor.mini)
     -1:06.7 editor:consolidate-selections (atom-text-editor.editor.mini)
     -1:06.7 core:cancel (atom-text-editor.editor.mini)
     -0:17.9 core:copy (atom-text-editor.editor.is-focused)
     -0:04.5 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:04.2 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:02.5 core:move-up (atom-text-editor.editor.is-focused)
     -0:00.0 core:move-down (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false
  },
  "react": {
    "jsxTagStartPattern": "(?x)((^|=|return)\\s*<([^!/?](?!. ?(</. ?>))))",
    "jsxComplexAttributePattern": "(?x)\\{ [^}\"']* $|\\( [^)\"']* $",
    "decreaseIndentForNextLinePattern": "(?x) />\\s*(,|;)?\\s*$ | ^\\s*\\S .*</[-_\\.A-Za-z0-9] >$"
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v0.3.0
linter, v0.10.1
linter-jshint, v0.1.0
linter-jsxhint, v0.1.0
linter-less, v0.3.1
linter-scss-lint, v0.0.11
react, v0.9.5

# Dev
No dev packages
```

/cc @atom/core

**Comment by orktes** [comment] 2015-01-28 19:44
Hi! Thanks for informing! Could not reproduce but made a fix that might help. New version published!

**Comment by orktes** [comment] 2015-01-28 19:45
Closing for now. Reopen if you are problem persists.

**Closed by orktes** 2015-01-28 19:45 UTC
